- name: melee
  hosts: melee
  vars:
    ip: "{{ ansible_tailscale0.ipv4.address }}"
  tasks:
    - name: /etc/kubernetes/pki/ca.key
      register: pki_ca_key
      stat:
        path: /etc/kubernetes/pki/ca.key
    - when: not pki_ca_key.stat.exists
      include_role:
        name: kubeadm-init
    - name: Enable kubelet
      systemd_service:
        name: kubelet.service
        enabled: true
        state: started
    - name: Copy kubeconfig
      become: true
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ../.kube/config
        flat: true
