[Container]
Environment=TS_AUTH_ONCE=true
Environment=TS_TAILSCALED_EXTRA_ARGS=--no-logs-no-support
#Environment=TS_EXTRA_ARGS="--advertise-tags=tag:quadlet"
Environment=TS_STATE_DIR=/var/lib/tailscale
Image=ghcr.io/tailscale/tailscale:latest
Mount=type=tmpfs,destination=/var/run/tailscale

[Service]
Restart=on-failure
