apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://127.0.0.1:2379
  labels:
    component: etcd
    tier: control-plane
    app: kine
  name: kine
  namespace: kube-system
spec:
  containers:
  - command:
    - kine
    - --listen-address=127.0.0.1:2379
    - --metrics-bind-address=0.0.0.0:2381
    - --server-cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --server-key-file=/etc/kubernetes/pki/etcd/server.key
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: ghcr.io/k3s-io/kine:v0.16.2@sha256:3be87cfae09425152050f1704bbe1e0a93893d9f0aaaf150ef4c5efe9501317a
    imagePullPolicy: IfNotPresent
    name: kine
    ports:
    - name: metrics
      hostPort: 2381
      containerPort: 2381
    volumeMounts:
    - mountPath: /db
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
    securityContext:
      runAsUser: 0
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
