apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://127.0.0.1:2379
  labels:
    component: etcd
    tier: control-plane
  name: kine
  namespace: kube-system
spec:
  containers:
  - command:
    - kine
    - --listen-address=127.0.0.1:2379
    - --metrics-bind-address=127.0.0.1:2381
    - --server-cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --server-key-file=/etc/kubernetes/pki/etcd/server.key
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: ghcr.io/k3s-io/kine:v0.14.15@sha256:74dbc3e5b4e2a7421f4fac732abc009a06795f9d6da868fb0c00b922b6bf02d2
    imagePullPolicy: IfNotPresent
    name: kine
    volumeMounts:
    - mountPath: /db
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
    securityContext:
      runAsUser: 0
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
