[groups]
  owner: lina-bh@github

[/film]
  /srv/film
  accs:
    r.: *

[/Music]
  /srv/Music
  accs:
    r.: *
    rwda.: @owner

[/downloads]
  /srv/downloads
  accs:
    r.: *
    rd.: @owner

[global]
rproxy: -1
xff-src: lan
ipar: 100.64.0.0/10
http-only
s-tbody: 0
idp-h-usr: Tailscale-User-Login
idp-store: 0
chmod-f: 664
chmod-d: 775
e2ts
e2ds
hist: /cfg/.hist
xvol
th-spec-p: 0
vol-or-crash
au-vol: 100
qdel: 1
nih
no-hash: .
rp-loc: srv

# Local Variables:
# tab-width: 2
# End:
