- name: Delete old kubeconfig
  file:
    path: ~/.kube/config
    state: absent
- name: Stop kubelet
  systemd_service:
    name: kubelet.service
    state: stopped
- name: Delete kubernetes directories
  become: true
  with_items:
    - /etc/cni
    - /etc/kubernetes
    - /opt/cni
    - /opt/libexec/kubernetes
    - /var/lib/etcd
  file:
    path: "{{ item }}"
    state: absent
- name: Copy defaults
  become: true
  with_items:
    - /etc/cni
    - /etc/kubernetes
  copy:
    remote_src: true
    src: "/usr{{ item }}"
    dest: "{{ item }}"
    force: true
- name: Restart CRI-O
  systemd_service:
    name: crio.service
    state: restarted
- name: Temporary kubeadm config file
  register: tmp
  tempfile:
- name: Template kubeadm config file
  template:
    src: configuration.kubeadm.k8s.io.yaml.j2
    dest: "{{ tmp.path }}"
- name: kubeadm init
  become: true
  command: kubeadm init --config="{{ tmp.path }}"
# - name: Copy /etc/kubernetes/admin.conf to unprivileged user
#   become: true
- name: Scale coredns to 1
  become: true
  command: kubectl --config=/etc/kubernetes/admin.conf --namespace=kube-system scale --replicas=1 deployment coredns
