[Container]
AddCapability=NET_ADMIN
AddCapability=NET_BIND_SERVICE
AddCapability=NET_RAW
AddDevice=/dev/net/tun
Environment=VPN_SERVICE_PROVIDER=airvpn
Environment=VPN_TYPE=wireguard
Environment=WIREGUARD_ADDRESSES='10.175.243.134/32,fd7d:76ee:e68f:a993:d653:927f:ba09:a626/128'
HealthCmd=/bin/true
HealthStartupCmd=nslookup example.org 127.0.0.1
HealthOnFailure=kill
HealthStartupRetries=2
Image=ghcr.io/qdm12/gluetun:latest
Notify=healthy
Secret=gluetun-key,type=env,target=WIREGUARD_PRIVATE_KEY
Secret=gluetun-psk,type=env,target=WIREGUARD_PRESHARED_KEY
StopSignal=SIGKILL

[Service]
Restart=on-failure
RestartMode=direct
