apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  annotations:
    tailscale.com/funnel: "false"
spec:
  defaultBackend:
    service:
      name: navidrome
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - n
