apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: monitoring
  name: kine
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      component: etcd
      app: kine
  podMetricsEndpoints:
  - portNumber: 2381
    scheme: HTTPS
    tlsConfig:
      insecureSkipVerify: true
