apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1k
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /srv
    type: Directory
