flags:
  no_logo: true
  no_version_check: true
  force_share_scan: true
shares:
  directories:
  - /srv/Music
  filters:
  - '.*/musiclibrary.db$'
  - '.*/Tyler, The Creator - Flower Boy/.*'
  - '.*/.+\.(png|jpg)'
  cache:
    storage_mode: disk
instance_name: agent
headless: true
web:
  https:
    disabled: true
relay:
  enabled: true
  mode: agent
  controller:
    address: http://controller:5030
metrics:
  enabled: true
  authentication:
    disabled: true
feature:
  swagger: true
