flags:
  no_logo: true
  no_version_check: true
  force_share_scan: true
shares:
  directories:
  - /srv/Music
  filters:
  - '.*/musiclibrary.db$'
  - '.*/.+\.(png|jpg)'
  - '.*/Fcukers - Ö/.*'
  cache:
    storage_mode: disk
directories:
  downloads: /srv/downloads
soulseek:
  listen_port: 34977
  description: "https://listenbrainz.org/user/WomenAndGamers/"
web:
  https:
    disabled: true
  authentication:
    disabled: true
groups:
  blacklisted:
    members:
    - perrin
    - footless4726
    - lazara007
    - NASferaturatyre
    - arrjayjay
    - SoularrFlare420
    - albers.craniotomy
    - vrrdnt
    - mirko72
    - teovader
    - newbt
instance_name: controller
relay:
  enabled: true
  mode: controller
  agents:
    agent:
      instance_name: agent
      secret: 4RSjR7IRfs95ZbR47xLYAL
metrics:
  enabled: true
  authentication:
    disabled: true
retention:
  logs: 1
  transfers:
    upload:
      succeeded: 1440
      errored: 1440
      cancelled: 1440
      failed: 1440
feature:
  swagger: true
