---
namespace: slskd
labels:
- pairs:
    app: slskd
resources:
- statefulset_controller.yaml
- svc_frontend.yaml
- svc_controller.yaml
- ingress.yaml
- pvc_srv.yaml
- pvc_apk-cache.yaml
configMapGenerator:
- name: slskd
  files:
  - controller.yml
images:
- name: slskd
  newName: ghcr.io/slskd/slskd
  newTag: 0.24.5@sha256:17ef977563be206f3b5932080b1e23883b2cb39dc9010640f6f39b4eaec887e3
