---
namespace: slskd
labels:
- pairs:
    app: slskd
resources:
- statefulset_controller.yaml
- svc_frontend.yaml
- svc_controller.yaml
- ingress.yaml
- pvc_srv.yaml
- pvc_apk-cache.yaml
configMapGenerator:
- name: slskd
  files:
  - controller.yml
images:
- name: slskd
  newName: ghcr.io/slskd/slskd
  newTag: 0.25.1@sha256:ab9ed50e028b524cefdb7c1dd8ebca368a076e18441ee8ac2326473eb850b4c3
