apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slskd
      relay: controller
  template:
    metadata:
      annotations:
        devices.crio.io: /dev/net/tun
      labels:
        app: slskd
        relay: controller
        frontend: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsGroup: 995
        fsGroup: 995
      initContainers:
      - name: snapshot
        image: docker.io/library/alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
        securityContext:
          runAsUser: 0
          seLinuxOptions:
            type: spc_t
          capabilities:
            drop:
            - ALL
            add:
            - SYS_ADMIN
        command:
        - /bin/sh
        - -c
        - "apk add btrfs-progs && (btrfs subvolume delete /srv/slskd; btrfs subvolume snapshot /srv/Music /srv/slskd)"
        volumeMounts:
        - name: apk-cache
          mountPath: /etc/apk/cache
        - name: srv
          mountPath: /srv
      - name: gluetun
        image: ghcr.io/qdm12/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
        restartPolicy: Always
        envFrom:
        - secretRef:
            name: gluetun
        lifecycle:
          stopSignal: SIGKILL
        readinessProbe:
          httpGet:
            port: 9999
          periodSeconds: 5
          timeoutSeconds: 5
          initialDelaySeconds: 10
        securityContext:
          runAsUser: 0
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - DAC_OVERRIDE
            - NET_ADMIN
            - NET_BIND_SERVICE
            - NET_RAW
      containers:
      - name: slskd
        image: slskd
        command:
        - /bin/sh
        - -c
        - 'umask 002 && exec /slskd/slskd'
        ports:
        - containerPort: 5030
        env:
        - name: SLSKD_CONFIG
          value: /config/controller.yml
        envFrom:
        - secretRef:
            name: slskd
        volumeMounts:
        - name: srv
          subPath: downloads
          mountPath: /srv/downloads
        - name: srv
          subPath: slskd
          mountPath: /srv/Music
          readOnly: true
          recursiveReadOnly: IfPossible
        - name: config
          mountPath: /config
        - name: data
          mountPath: /app/data
        securityContext:
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
      volumes:
      - name: srv
        persistentVolumeClaim:
          claimName: srv
      - name: config
        configMap:
          name: slskd
      - name: apk-cache
        persistentVolumeClaim:
          claimName: apk-cache
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: local-path
      accessModes:
      - ReadWriteOncePod
      resources:
        requests:
          storage: 8Mi

