apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent
spec:
  replicas: 0
  selector:
    matchLabels:
      app: slskd
      relay: agent
  template:
    metadata:
      labels:
        app: slskd
        relay: agent
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsGroup: 995
        fsGroup: 995
      initContainers:
      - name: snapshot
        image: docker.io/library/alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
        securityContext:
          runAsUser: 0
          seLinuxOptions:
            type: spc_t
          capabilities:
            drop:
            - ALL
            add:
            - SYS_ADMIN
        command:
        - /bin/sh
        - -c
        - "apk add btrfs-progs && (btrfs subvolume delete /srv/slskd; btrfs subvolume snapshot /srv/Music /srv/slskd)"
        volumeMounts:
        - name: apk-cache
          mountPath: /etc/apk/cache
        - name: srv
          mountPath: /srv
      containers:
      - name: slskd
        image: slskd
        command:
        - /slskd/slskd
        env:
        - name: SLSKD_CONFIG
          value: /config/agent.yml
        envFrom:
        - secretRef:
            name: agent
        ports:
        - containerPort: 5030
        volumeMounts:
        - name: srv
          subPath: slskd
          mountPath: /srv/Music
          readOnly: true
          recursiveReadOnly: IfPossible
        - name: config
          mountPath: /config
        - name: data
          mountPath: /app/data
        securityContext:
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
      volumes:
      - name: srv
        persistentVolumeClaim:
          claimName: srv
      - name: config
        configMap:
          name: slskd
      - name: apk-cache
        persistentVolumeClaim:
          claimName: apk-cache
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: local-path
      accessModes:
      - ReadWriteOncePod
      resources:
        requests:
          storage: 8Mi

