apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://127.0.0.1:2379
  labels:
    component: etcd
    tier: control-plane
  name: kine
  namespace: kube-system
spec:
  containers:
  - command:
    - kine
    - --listen-address=127.0.0.1:2379
    - --server-cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --server-key-file=/etc/kubernetes/pki/etcd/server.key
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: ghcr.io/k3s-io/kine:latest
    imagePullPolicy: IfNotPresent
    # livenessProbe:
    #   failureThreshold: 8
    #   httpGet:
    #     host: 127.0.0.1
    #     path: /livez
    #     port: probe-port
    #     scheme: HTTP
    #   initialDelaySeconds: 10
    #   periodSeconds: 10
    #   timeoutSeconds: 15
    name: kine
    # ports:
    # - containerPort: 2381
    #   name: probe-port
    #   protocol: TCP
    # readinessProbe:
    #   failureThreshold: 3
    #   tcpSocket:
    #     port: 2379
    #   periodSeconds: 1
    #   timeoutSeconds: 15
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 100Mi
    # startupProbe:
    #   failureThreshold: 24
    #   httpGet:
    #     host: 127.0.0.1
    #     path: /readyz
    #     port: probe-port
    #     scheme: HTTP
    #   initialDelaySeconds: 10
    #   periodSeconds: 10
    #   timeoutSeconds: 15
    volumeMounts:
    - mountPath: /db
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
    securityContext:
      runAsUser: 0
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
