- name: melee
  hosts: melee
  vars:
    ip: "{{ ansible_tailscale0.ipv4.address }}"
  tasks:
    - name: /etc/kubernetes/pki/ca.key
      register: pki_ca_key
      stat:
        path: /etc/kubernetes/pki/ca.key
    - name: Temporary kubeadm config file
      register: tmp
      tempfile:
    - name: Template kubeadm config file
      template:
        src: ./configuration.kubeadm.k8s.io.yaml.j2
        dest: "{{ tmp.path }}"
    - when: not pki_ca_key.stat.exists
      include_tasks: kubeadm-init.yaml
    - name: Enable kubelet
      systemd_service:
        name: kubelet.service
        enabled: true
        state: started
    - name: Copy kubeconfig
      become: true
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ../.kube/config
        flat: true
