on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # daily at midnight
  workflow_dispatch:
jobs:
  build:
    name: Build and push ghcr.io/${{ github.repository }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      NAME: ghcr.io/${{ github.repository }}
    steps:
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: ${{ env.REGISTRY }}
    - uses: actions/checkout@v6
    - name: Build ghcr.io/${{ github.repository }}:latest
      run: make build NAME=${{ env.NAME }} EXTRA_BUILD_ARGS='--label=org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}'
    - name: Push latest
      run: make push NAME=${{ env.NAME }}
    - name: Push ${{ github.sha }}
      run: make push_HEAD NAME=${{ env.NAME }}
