---
jobs:
  check:
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
    runs-on: ubuntu-latest
    steps:
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@50c2d9a331bb67c8fdab99b86455fad05e2e3252 # v2
      with:
        password: ${{ github.token }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
    - id: check-upgrade
      name: dnf check-upgrade --security
      run: |
        rc=255
        podman run --rm --entrypoint= "ghcr.io/${{ github.repository }}:latest" dnf5 check-upgrade --refresh --security || rc="$?"
        if [ "$rc" -eq 0 ]; then
          exit 0
        fi
        if [ "$rc" -ne 100 ]; then
          exit "$rc"
        fi
        printf 'rc=%s\n' "$rc" >> "$GITHUB_OUTPUT"
    - env:
        GH_TOKEN: ${{ github.token }}
      if: steps.check-upgrade.outputs.rc == '100'
      name: Dispatch build
      run: gh workflow run build.yml --repo "$GITHUB_REPOSITORY"
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  actions: write
  packages: read
